---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: applications
spec:
  chart:
    spec:
      chart: ./chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: basic-api
  interval: 1m0s

